name: Release

on:
  # TODO: Remove when done testing
  pull_request:
    branches: [main]
  # TODO: Uncomment when done testing
  # push:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Needed by the action-gh-release action
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Detect version change and create release
        id: check-for-changes
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git fetch --tags
          if ! git tag | grep -q "^$VERSION$"; then
            # Version bump detected
            echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
          fi
          # TODO: Forcing
          echo "VERSION=0.0.6" >> "$GITHUB_OUTPUT"
      # - name: Process Changes
      #   run: |
      #     echo "Going to create a release"
      #   if: ${{ steps.check-for-changes.outputs.VERSION != '' }}
      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.check-for-changes.outputs.VERSION }}
          name: ${{ steps.check-for-changes.outputs.VERSION }}
          # TODO: Clean up to main
          target_commitish: schedule-fetch
          generate_release_notes: true
          # body_path: ${{ github.workspace }}-CHANGELOG.txt
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          # token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        if: ${{ steps.check-for-changes.outputs.VERSION != '' }}


      # TODO: Eval this
      # - name: Create Release
      #   if: env.VERSION != ''
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ env.VERSION }}
      #     release_name: ${{ env.VERSION }}
      #     draft: false
      #     prerelease: false
