name: Release

on:
  # TODO: Remove when done testing
  pull_request:
    branches: [main]
  # TODO: Uncomment when done testing
  # push:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Detect version change and create release
        id: check-for-changes
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git fetch --tags
          if ! git tag | grep -q "^$VERSION$"; then
            # Version bump detected
            echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
          fi
      - name: Process Changes
        run: |
          echo "Going to create a release"
        if: ${{ steps.check-for-changes.outputs.VERSION != '' }}

      # - name: Create Release
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')


      # TODO: Eval this
      # - name: Create Release
      #   if: env.VERSION != ''
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ env.VERSION }}
      #     release_name: ${{ env.VERSION }}
      #     draft: false
      #     prerelease: false
